Verifica tener el kernel seleccionado como `tu_entorno`

In [1]:
import pandas as pd

Las funciones para scraping y obtencion de datos se encuentran en `functions.py`

In [3]:
from functions import DescargadorExcel

# Crear una instancia de la clase con la URL base
enacom = DescargadorExcel(url_base='https://indicadores.enacom.gob.ar')

# URL de la página donde se encuentra el archivo
page_url = 'https://indicadores.enacom.gob.ar/datos-abiertos'
link_text = 'Internet'  # archivo que busco

# Obtener y listar las hojas del archivo Excel
paginador = enacom.obtener_y_listar_hojas(page_url, link_text)
paginador

['Acc_vel_loc_sinrangos',
 'Velocidad_sin_Rangos',
 'Accesos_tecnologia_localidad',
 'Velocidad % por prov',
 'Totales VMD',
 'Totales Accesos Por Tecnología',
 'Accesos Por Tecnología',
 'Penetración-poblacion',
 'Penetracion-hogares',
 'Penetracion-totales',
 'Totales Accesos por rango',
 'Accesos por rangos',
 'Dial-BAf',
 'Totales Dial-BAf',
 'Ingresos ']

Creamos un dataframe para cada hoja del excel. Luego decidiremos cual hoja sera exportada y necesaria para nuestro analisis.

In [29]:
# Datos de acceso por localidad sin rangos de velocidad.
acc_vel_loc_sinrangos = enacom.obtener_y_leer_hoja(page_url, link_text, 0)
acc_vel_loc_sinrangos.head()

        Partido   Localidad  link Indec Velocidad (Mbps)  Provincia  Accesos
0  BUENOS AIRES  25 de Mayo  25 de Mayo          6854100       0.00      1.0
1  BUENOS AIRES  25 de Mayo  25 de Mayo          6854100       0.50      2.0
2  BUENOS AIRES  25 de Mayo  25 de Mayo          6854100       0.75     19.0
3  BUENOS AIRES  25 de Mayo  25 de Mayo          6854100       3.00     85.0
4  BUENOS AIRES  25 de Mayo  25 de Mayo          6854100       3.50    145.0

In [10]:
# Información sobre la velocidad de conexión a internet sin rangos específicos.
velocidad_sin_Rangos = enacom.obtener_y_leer_hoja(page_url, link_text, 1)
velocidad_sin_Rangos.head()

    Año  Trimestre     Provincia  Velocidad  Accesos
0  2024          2  BUENOS AIRES       75.0     1062
1  2024          2  BUENOS AIRES       59.0       59
2  2024          2  BUENOS AIRES      480.0        5
3  2024          2  BUENOS AIRES        3.5    41735
4  2024          2  BUENOS AIRES       18.0     1042

In [11]:
#  Accesos a internet por tipo de tecnología y localidad.
accesos_tecnologia_localidad = enacom.obtener_y_leer_hoja(page_url, link_text, 2)
accesos_tecnologia_localidad.head()

      Provincia     Partido   Localidad    Tecnologia Link Indec  Accesos
0  BUENOS AIRES  25 de Mayo  25 de Mayo          ADSL    6854100    755.0
1  BUENOS AIRES  25 de Mayo  25 de Mayo    CABLEMODEM    6854100   4600.0
2  BUENOS AIRES  25 de Mayo  25 de Mayo  FIBRA OPTICA    6854100      2.0
3  BUENOS AIRES  25 de Mayo  25 de Mayo     SATELITAL    6854100    742.0
4  BUENOS AIRES  25 de Mayo  25 de Mayo      WIRELESS    6854100    727.0

In [12]:
# Distribución porcentual de la velocidad de conexión a internet por provincia.
velocidad_porc_prov = enacom.obtener_y_leer_hoja(page_url, link_text, 3)
velocidad_porc_prov.head()

    Año  Trimestre        Provincia  Mbps (Media de bajada)
0  2024          2     Buenos Aires                  157.41
1  2024          2  Capital Federal                  233.01
2  2024          2        Catamarca                   97.38
3  2024          2            Chaco                  107.76
4  2024          2           Chubut                   21.67

In [13]:
# Totales de velocidad media descargada (VMD)
totales_VMD = enacom.obtener_y_leer_hoja(page_url, link_text, 4)
totales_VMD.head()

    Año  Trimestre  Mbps (Media de bajada)    Trimestre.1
0  2024          2                  139.25   Abr-Jun 2024
1  2024          1                  139.15   Ene-Mar 2024
2  2023          4                  139.04   Oct-Dic 2023
3  2023          3                  129.67  Jul-Sept 2023
4  2023          2                  123.95   Abr-Jun 2023

In [14]:
# Totales de accesos a internet desglosados por tecnología.
totales_Accesos_Por_Tecnología = enacom.obtener_y_leer_hoja(page_url, link_text, 5)
totales_Accesos_Por_Tecnología.head()

,Año,Trimestre,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total,Periodo
0,2024,2,733491,5867504,4169958,593197,191957,11556107,Abr-Jun 2024
1,2024,1,774475,5986957,4015101,598682,257941,11633156,Ene-Mar 2024
2,2023,4,836390,6022532,3908183,585760,194796,11547661,Oct-Dic 2023
3,2023,3,897895,6018832,3708718,581436,200027,11406908,Jul-Sept 2023
4,2023,2,1006509,5997149,3463988,581823,202428,11251897,Abr-Jun 2023

In [15]:
# Totales de accesos a internet desglosados por tecnología.
accesos_Por_Tecnología = enacom.obtener_y_leer_hoja(page_url, link_text, 6)
accesos_Por_Tecnología.head()

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
0,2024,2,Buenos Aires,214055.0,2722466.0,1849476.0,138638.0,64745.0,4989380.0
1,2024,2,Capital Federal,54102.0,1144781.0,230402.0,4493.0,29821.0,1463599.0
2,2024,2,Catamarca,4951.0,10303.0,58355.0,1384.0,81.0,75074.0
3,2024,2,Chaco,9448.0,57935.0,68944.0,8407.0,2358.0,147092.0
4,2024,2,Chubut,25955.0,80704.0,26516.0,31118.0,9930.0,174223.0

In [16]:
# Penetración de internet en la población.
penetración_poblacion = enacom.obtener_y_leer_hoja(page_url, link_text, 7)
penetración_poblacion.head()

    Año  Trimestre        Provincia  Accesos por cada 100 hab
0  2024          2     Buenos Aires                     27.43
1  2024          2  Capital Federal                     47.44
2  2024          2        Catamarca                     17.50
3  2024          2            Chaco                     11.78
4  2024          2           Chubut                     26.46

In [17]:
# Penetración de internet en hogares.
penetracion_hogares = enacom.obtener_y_leer_hoja(page_url, link_text, 8)
penetracion_hogares.head()

    Año  Trimestre        Provincia  Accesos por cada 100 hogares
0  2024          2     Buenos Aires                         79.84
1  2024          2  Capital Federal                        116.37
2  2024          2        Catamarca                         68.81
3  2024          2            Chaco                         44.06
4  2024          2           Chubut                         86.33

In [18]:
# Totales de penetración de internet.
penetracion_totales = enacom.obtener_y_leer_hoja(page_url, link_text, 9)
penetracion_totales.head()

,Año,Trimestre,Accesos por cada 100 hogares,Accesos por cada 100 hab,Periodo
0,2024,2,78.13,24.57,Abr-Jun 2024
1,2024,1,78.89,24.79,Ene-Mar 2024
2,2023,4,78.56,24.66,Oct-Dic 2023
3,2023,3,77.84,24.41,Jul-Sept 2023
4,2023,2,77.02,24.14,Abr-Jun 2023

In [19]:
# Totales de accesos a internet desglosados por velocidad de conexión.
totales_Accesos_por_velocidad =enacom.obtener_y_leer_hoja(page_url, link_text, 10)
totales_Accesos_por_velocidad.head()

,Año,Trimestre,Hasta 512 kbps,Entre 512 Kbps y 1 Mbps,Entre 1 Mbps y 6 Mbps,Entre 6 Mbps y 10 Mbps,Entre 10 Mbps y 20 Mbps,Entre 20 Mbps y 30 Mbps,Más de 30 Mbps,OTROS,Total
0,2024,2,28151,67024,840200,911374,662649,348253,8357088,341368,11556107
1,2024,1,28801,69355,866152,950930,672155,353896,8363694,328173,11633156
2,2023,4,29708,71742,900253,978108,697232,350290,8224736,295592,11547661
3,2023,3,30274,80609,945608,998725,720084,350918,8003269,277421,11406908
4,2023,2,30827,79405,963510,1028250,734125,364730,7775095,275955,11251897

In [20]:
# Accesos a internet desglosados por velocidad de conexión.
accesos_por_velocidad = enacom.obtener_y_leer_hoja(page_url, link_text, 11)
accesos_por_velocidad.head()

,Año,Trimestre,Provincia,HASTA 512 kbps,+ 512 Kbps - 1 Mbps,+ 1 Mbps - 6 Mbps,+ 6 Mbps - 10 Mbps,+ 10 Mbps - 20 Mbps,+ 20 Mbps - 30 Mbps,+ 30 Mbps,OTROS,Total
0,2024,2,Buenos Aires,25287.0,23034.0,222627.0,221660.0,244528.0,106302.0,4020395.0,125547.0,4989380.0
1,2024,2,Capital Federal,518.0,4122.0,24539.0,40296.0,33158.0,5633.0,1355333.0,0.0,1463599.0
2,2024,2,Catamarca,72.0,164.0,2660.0,3093.0,3799.0,1279.0,63954.0,53.0,75074.0
3,2024,2,Chaco,236.0,349.0,14594.0,8336.0,6208.0,6454.0,107707.0,3208.0,147092.0
4,2024,2,Chubut,125.0,1139.0,43699.0,31971.0,22696.0,19827.0,38212.0,16554.0,174223.0

In [21]:
# Accesos dial-up y Banda Ancha Fija (BAf)
dial_BAf = enacom.obtener_y_leer_hoja(page_url, link_text, 12)
dial_BAf.head()

    Año  Trimestre        Provincia  Banda ancha fija  Dial up    Total
0  2024          2     Buenos Aires           4983480   5900.0  4989380
1  2024          2  Capital Federal           1461549   2050.0  1463599
2  2024          2        Catamarca             75073      1.0    75074
3  2024          2            Chaco            147087      5.0   147092
4  2024          2           Chubut            173366    857.0   174223

In [22]:
# Totales de accesos dial-up y Banda Ancha Fija (BAf).
totales_Dial_BAf = enacom.obtener_y_leer_hoja(page_url, link_text, 13)
totales_Dial_BAf.head()

    Año  Trimestre  Banda ancha fija  Dial up     Total        Periodo
0  2024          2          11544314    11793  11556107   Abr-Jun 2024
1  2024          1          11621363    11793  11633156   Ene-Mar 2024
2  2023          4          11535868    11793  11547661   Oct-Dic 2023
3  2023          3          11395115    11793  11406908  Jul-Sept 2023
4  2023          2          11239781    12116  11251897   Abr-Jun 2023

In [23]:
#  Ingresos generados por los servicios de internet en miles de pesos.
ingresos = enacom.obtener_y_leer_hoja(page_url, link_text, 14)
ingresos.head()

    Año  Trimestre  Ingresos (miles de pesos)        Periodo
0  2024          2               4.420322e+08   Abr-Jun 2024
1  2024          1               3.461990e+08   Ene-Mar 2024
2  2023          4               1.673760e+08   Oct-Dic 2023
3  2023          3               1.331066e+08  Jul-Sept 2023
4  2023          2               1.180603e+08   Jun-Mar 2023

Exportar las hojas.

In [612]:
accesos_Por_Tecnología.Año = accesos_Por_Tecnología['Año'].astype(str).str.replace('*', '', regex=False).str.strip() # Quitar los * , '' de 2019
accesos_Por_Tecnología.Trimestre = accesos_Por_Tecnología['Trimestre'].astype(str).str.replace('*', '', regex=False).str.strip() # Quitar los * , ''
threshold = len(accesos_Por_Tecnología.columns) * 0.8
accesos_Por_Tecnología = accesos_Por_Tecnología.dropna(thresh=threshold) # Eliminar filas con más del 80% de columnas nulas
accesos_Por_Tecnología.loc[:, 'Año'] = accesos_Por_Tecnología['Año'].dropna().astype(int)  # Eliminar NaN y convertir a enteros

accesos_Por_Tecnología.to_csv('../data/acc_x_tecnologia.csv',index=False)

In [613]:
dial_BAf = dial_BAf[dial_BAf['Trimestre'] == 1]
dial_BAf.to_csv('../data/dial_baf.csv',index=False)

totales_Dial_BAf.to_csv('../data/dial_total.csv',index=False)
penetracion_totales.to_csv('../data/p_total.csv',index=False)
totales_Accesos_Por_Tecnología.to_csv('../data/tec_total.csv',index=False)
velocidad_porc_prov.to_csv('../data/vel_prov.csv',index=False)
totales_VMD.to_csv('../data/vel_total.csv',index=False)
penetracion_hogares.to_csv('../data/p_hogar.csv',index=False)

## Datos de Inflación

Los datos de inflación utilizados en este análisis fueron obtenidos de la página oficial del Instituto Nacional de Estadística y Censos (INDEC) de Argentina. La fuente de los datos es el Índice de Precios al Consumidor (IPC) con cobertura nacional.

Puedes consultar los datos originales en el siguiente enlace proporcionado por el INDEC:

[Índice de Precios al Consumidor - INDEC](https://www.indec.gob.ar/indec/web/Nivel4-Tema-3-5-31)

Los datos descargados incluyen información sobre la inflación mensual en Argentina, que se ha procesado y analizado para obtener estadísticas trimestrales de inflación.

In [4]:
import requests
import pandas as pd
import io

# URL completa del archivo Excel de INDEC
url_excel = 'https://www.indec.gob.ar/ftp/cuadros/economia/sh_ipc_12_24.xls'

# Descargar el archivo Excel
response = requests.get(url_excel)

# Verificar que la solicitud fue exitosa para el archivo Excel
if response.status_code == 200:
    # Leer el contenido del archivo Excel en un DataFrame
    indec = pd.read_excel(io.BytesIO(response.content), sheet_name=None, engine='xlrd')  # Usar 'xlrd' para archivos .xls
    paginador = list(indec.keys())
    print(paginador)
else:
    print(f"Error al descargar el archivo: {response.status_code}")

['Variación mensual IPC Nacional', 'Var. interanual IPC Nacional', 'Índices IPC Cobertura Nacional', 'IPC GBA Base dic 2016', 'IPC GBA Abril 2016-Mayo 2017', 'Ponderaciones']

In [5]:
ipc = indec[paginador[0]] # Leer la hoja
ipc = ipc.iloc[[0]] # Ver en que fila comienza el dataset 
ipc

,Índice de precios al consumidor con cobertura nacional. Resultados por región,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95
0,Período de referencia: Diciembre 2016=100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
ipc = indec[paginador[0]] # Leer la hoja
ipc = ipc.iloc[[4, 8]] # Seleccionar (mes,nivel genral). 
ipc

,Índice de precios al consumidor con cobertura nacional. Resultados por región,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92
4,Total nacional,2017-01-01 00:00:00,2017-02-01 00:00:00,2017-03-01 00:00:00,2017-04-01 00:00:00,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,...,2023-11-01 00:00:00,2023-12-01 00:00:00,2024-01-01 00:00:00,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00,2024-08-01 00:00:00
8,Nivel general,1.6,2.1,2.4,2.7,1.4,1.2,1.7,1.4,1.9,...,12.8,25.5,20.6,13.2,11,8.8,4.2,4.6,4,4.2

In [21]:
ipc.columns = ipc.iloc[0] # La primera fila como columnas.
ipc = ipc.T # Transponer el dataframe
ipc.columns = ipc.iloc[0] # La primera fila como columnas.
ipc = ipc[1:] # Quitar la pprimera fila
ipc.index.name = None
ipc.reset_index(drop=True, inplace=True) # Restablecer el índice para que sea numérico

ipc

Total nacional       Total nacional Nivel general
0               2017-01-01 00:00:00           1.6
1               2017-02-01 00:00:00           2.1
2               2017-03-01 00:00:00           2.4
3               2017-04-01 00:00:00           2.7
4               2017-05-01 00:00:00           1.4
..                              ...           ...
87              2024-04-01 00:00:00           8.8
88              2024-05-01 00:00:00           4.2
89              2024-06-01 00:00:00           4.6
90              2024-07-01 00:00:00             4
91              2024-08-01 00:00:00           4.2

[92 rows x 2 columns]

In [616]:
ipc['Total nacional'] = ipc['Total nacional'].apply(lambda x: pd.to_datetime(x).strftime('%Y-%m') if pd.to_datetime(x, errors='coerce') is not pd.NaT else x)
ipc['Total nacional'] = pd.to_datetime(ipc['Total nacional'], errors='coerce')

# Tomar solo hasta Marzo. que es hasta donde llegan los ingresos.
ipc = ipc[ipc['Total nacional'] <= '2024-03-01']

# Calcular la inflacion trimestral
ipc.set_index('Total nacional', inplace=True)
ipc = ipc.resample('QE').sum()
ipc = ipc.reset_index()
ipc['Año'] = ipc['Total nacional'].dt.year
ipc['Trimestre'] = ipc['Total nacional'].dt.quarter
ipc['Nivel general'] = ipc['Nivel general'].astype(float)
ipc = ipc.drop(columns=['Total nacional'])

ipc.head()

Total nacional  Nivel general   Año  Trimestre
0                         6.1  2017          1
1                         5.3  2017          2
2                         5.0  2017          3
3                         6.0  2017          4
4                         6.5  2018          1

In [617]:
ingresos.loc[ingresos['Año'] == 2033, 'Año'] = 2023 # Modificar un error del df.
ingresos = pd.merge(ingresos, ipc, on=['Año', 'Trimestre'], how='left') # merge para combinar los DataFrames por Año y Trimestre
ingresos.dropna(subset=['Nivel general'], inplace=True)

ingresos.to_csv('../data/ingresos.csv',index=False)